name: CaptureThePortal
main: org.wargamer2010.capturetheportal.CaptureThePortal
version: 1.9.3
author: Wargamer2010
description: "Capture the Portal by holding the wool square"             
commands:
  capturetheportal:
    description: Admin commands for CaptureThePortal
    usage: /capturetheportal [reload]